### ISSUE TITLE
Program crash when a Microsoft reserved name is used

### ISSUE THREAD

**Issue by AlanParadis** [OverLore/Advanced-C-files-and-headers-generator#1]
When CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9 are use as a name in the generator the program crash because those name are [reserved name](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#:~:text=Do%20not%20use%20the%20following,txt%20is%20not%20recommended.) by Microsoft

**Comment by OverLore** [comment]
Fixed with v0.4
